version: "3.8"

services:
  nopcommerce_database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: nopcommerce_mssql
    environment:
      SA_PASSWORD: "StrongPassword!123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - nopcommerce_db:/var/opt/mssql
    restart: unless-stopped

  nopcommerce_web:
    image: nopcommerceteam/nopcommerce:latest
    container_name: nopcommerce_web
    ports:
      - "8080:80"
    depends_on:
      - nopcommerce_database
    restart: unless-stopped

volumes:
  nopcommerce_db:
