# Исправьте docker-compose.yml
  cat > 02-local-mock-nopcommerce/docker-compose.yml << 'EOF'
version: '3.8'

services:
  nopcommerce_web:
    image: nopcommerce/nopcommerce:latest
    container_name: nopcommerce
    ports:
      - "8080:80"
    depends_on:
      - nopcommerce_database
    environment:
      Nop.Data.ConnectionString: "Server=nopcommerce_database;Database=nopCommerce;User ID=sa;Password=nopCommerce_db_password;Trusted_Connection=False;MultipleActiveResultSets=True;TrustServerCertificate=True"

  nopcommerce_database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: nopcommerce_mssql_server
    environment:
      SA_PASSWORD: "nopCommerce_db_password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

volumes:
  nopcommerce_data:
